// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenManual_screen_init(void)
{
    ui_ScreenManual = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenManual, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainBackground = lv_obj_create(ui_ScreenManual);
    lv_obj_set_width(ui_MainBackground, lv_pct(100));
    lv_obj_set_height(ui_MainBackground, lv_pct(100));
    lv_obj_set_align(ui_MainBackground, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainBackground, lv_color_hex(0x5A6A8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftPanel = lv_obj_create(ui_ScreenManual);
    lv_obj_set_width(ui_LeftPanel, 75);
    lv_obj_set_height(ui_LeftPanel, lv_pct(100));
    lv_obj_set_align(ui_LeftPanel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_LeftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LeftPanel, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenAutoBackgroundPicture1 = lv_img_create(ui_ScreenManual);
    lv_img_set_src(ui_ScreenAutoBackgroundPicture1, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_ScreenAutoBackgroundPicture1, 800);
    lv_obj_set_height(ui_ScreenAutoBackgroundPicture1, 480);
    lv_obj_set_align(ui_ScreenAutoBackgroundPicture1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenAutoBackgroundPicture1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_NotificationPanel = lv_obj_create(ui_ScreenManual);
    lv_obj_set_width(ui_NotificationPanel, 673);
    lv_obj_set_height(ui_NotificationPanel, 48);
    lv_obj_set_x(ui_NotificationPanel, 36);
    lv_obj_set_y(ui_NotificationPanel, -9);
    lv_obj_set_align(ui_NotificationPanel, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_NotificationPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_NotificationPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NotificationPanel, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NotificationPanel, lv_color_hex(0x181C20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NotificationPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NotificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_NotificationPanel, lv_color_hex(0x4D5A75), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_NotificationPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_NotificationPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_NotificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenAutoHeader1 = lv_obj_create(ui_ScreenManual);
    lv_obj_set_width(ui_ScreenAutoHeader1, 665);
    lv_obj_set_height(ui_ScreenAutoHeader1, 40);
    lv_obj_set_x(ui_ScreenAutoHeader1, -30);
    lv_obj_set_y(ui_ScreenAutoHeader1, 0);
    lv_obj_set_align(ui_ScreenAutoHeader1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ScreenAutoHeader1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAutoHeader1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAutoHeader1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenAutoHeader1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenAutoHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenAutoHeader1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAutoHeader1 = lv_label_create(ui_ScreenAutoHeader1);
    lv_obj_set_width(ui_LabelAutoHeader1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAutoHeader1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAutoHeader1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelAutoHeader1, _("Press to Start"));
    lv_label_set_recolor(ui_LabelAutoHeader1, "true");
    lv_obj_set_style_text_color(ui_LabelAutoHeader1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAutoHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAutoHeader1, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeaderVersionNumber = lv_label_create(ui_ScreenAutoHeader1);
    lv_obj_set_width(ui_LabelHeaderVersionNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeaderVersionNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHeaderVersionNumber, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelHeaderVersionNumber, "version");
    lv_label_set_recolor(ui_LabelHeaderVersionNumber, "true");
    lv_obj_set_style_text_color(ui_LabelHeaderVersionNumber, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeaderVersionNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeaderVersionNumber, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuPrint1 = lv_img_create(ui_ScreenManual);
    lv_img_set_src(ui_BTNAutoMenuPrint1, &ui_img_photoshoped_assets_chinese_manual_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint1, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint1, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove1 = lv_img_create(ui_ScreenManual);
    lv_img_set_src(ui_BTNAutoMenuMove1, &ui_img_photoshoped_assets_chinese_timer_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuMove1, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove1, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuMove1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuSetting1 = lv_img_create(ui_ScreenManual);
    lv_img_set_src(ui_BTNAutoMenuSetting1, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting1, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting1, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenAutoContentPanel1 = lv_obj_create(ui_ScreenManual);
    lv_obj_set_width(ui_ScreenAutoContentPanel1, 720);
    lv_obj_set_height(ui_ScreenAutoContentPanel1, 430);
    lv_obj_set_align(ui_ScreenAutoContentPanel1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ScreenAutoContentPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAutoContentPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenAutoContentPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenAutoContentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplayTempRemainCountdown2 = lv_obj_create(ui_ScreenAutoContentPanel1);
    lv_obj_set_width(ui_DisplayTempRemainCountdown2, 165);
    lv_obj_set_height(ui_DisplayTempRemainCountdown2, 210);
    lv_obj_set_x(ui_DisplayTempRemainCountdown2, -34);
    lv_obj_set_y(ui_DisplayTempRemainCountdown2, 15);
    lv_obj_set_align(ui_DisplayTempRemainCountdown2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_DisplayTempRemainCountdown2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DisplayTempRemainCountdown2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplayTempRemainCountdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DisplayTempRemainCountdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DisplayTempRemainCountdown2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DisplayTempRemainCountdown2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DisplayTempRemainCountdown2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DisplayTempRemainCountdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperaturePanel1 = lv_obj_create(ui_DisplayTempRemainCountdown2);
    lv_obj_set_width(ui_TemperaturePanel1, lv_pct(100));
    lv_obj_set_height(ui_TemperaturePanel1, lv_pct(50));
    lv_obj_set_align(ui_TemperaturePanel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TemperaturePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TemperaturePanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperaturePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_TemperaturePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_TemperaturePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TemperaturePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature4 = lv_label_create(ui_TemperaturePanel1);
    lv_obj_set_width(ui_LabelSensorTemperature4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTemperature4, lv_pct(0));
    lv_obj_set_y(ui_LabelSensorTemperature4, lv_pct(-13));
    lv_obj_set_align(ui_LabelSensorTemperature4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature4, _("Temp"));
    lv_label_set_recolor(ui_LabelSensorTemperature4, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature4, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature4, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTempValue1 = lv_label_create(ui_TemperaturePanel1);
    lv_obj_set_width(ui_LabelSensorTempValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTempValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTempValue1, lv_pct(0));
    lv_obj_set_y(ui_LabelSensorTempValue1, lv_pct(10));
    lv_obj_set_align(ui_LabelSensorTempValue1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSensorTempValue1, "...");
    lv_obj_set_style_text_color(ui_LabelSensorTempValue1, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTempValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTempValue1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splitter3 = lv_obj_create(ui_DisplayTempRemainCountdown2);
    lv_obj_set_height(ui_Splitter3, 2);
    lv_obj_set_width(ui_Splitter3, lv_pct(50));
    lv_obj_set_align(ui_Splitter3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Splitter3, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splitter3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Splitter3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Splitter3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Splitter3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperaturePanel2 = lv_obj_create(ui_DisplayTempRemainCountdown2);
    lv_obj_set_width(ui_TemperaturePanel2, lv_pct(100));
    lv_obj_set_height(ui_TemperaturePanel2, lv_pct(50));
    lv_obj_set_x(ui_TemperaturePanel2, lv_pct(0));
    lv_obj_set_y(ui_TemperaturePanel2, lv_pct(50));
    lv_obj_set_align(ui_TemperaturePanel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TemperaturePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TemperaturePanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperaturePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_TemperaturePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_TemperaturePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TemperaturePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature5 = lv_label_create(ui_TemperaturePanel2);
    lv_obj_set_width(ui_LabelSensorTemperature5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTemperature5, lv_pct(0));
    lv_obj_set_y(ui_LabelSensorTemperature5, lv_pct(-13));
    lv_obj_set_align(ui_LabelSensorTemperature5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature5, _("Countdown"));
    lv_label_set_recolor(ui_LabelSensorTemperature5, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature5, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature5, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTempValue2 = lv_label_create(ui_TemperaturePanel2);
    lv_obj_set_width(ui_LabelSensorTempValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTempValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTempValue2, lv_pct(0));
    lv_obj_set_y(ui_LabelSensorTempValue2, lv_pct(20));
    lv_obj_set_align(ui_LabelSensorTempValue2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSensorTempValue2, "03:00");
    lv_obj_set_style_text_color(ui_LabelSensorTempValue2, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTempValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTempValue2, &ui_font_Chinese_48_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Buttons_S1 = lv_obj_create(ui_ScreenAutoContentPanel1);
    lv_obj_set_width(ui_Panel_Buttons_S1, 180);
    lv_obj_set_height(ui_Panel_Buttons_S1, 180);
    lv_obj_set_x(ui_Panel_Buttons_S1, -31);
    lv_obj_set_y(ui_Panel_Buttons_S1, -18);
    lv_obj_set_align(ui_Panel_Buttons_S1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Panel_Buttons_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Buttons_S1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Buttons_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNStartMenu1 = lv_img_create(ui_Panel_Buttons_S1);
    lv_img_set_src(ui_BTNStartMenu1, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTNStartMenu1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNStartMenu1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNStartMenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNStartMenu1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNStartMenuTop1 = lv_img_create(ui_BTNStartMenu1);
    lv_img_set_src(ui_BTNStartMenuTop1, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTNStartMenuTop1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNStartMenuTop1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNStartMenuTop1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNStartMenuTop1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTNStartMenuTop1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTNStartMenuTop1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTNStartMenuTop1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNStartMenuTop1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTNStartMenuTop1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTNStartMenuTop1, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTNStartMenuTop1, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_BTNStartMenuTop1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_BTNStartMenuTop1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTNStartMenuTop1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNStartMenuTop1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNStartMenuTop1, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNStartMenuTop1, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_BTNStartMenuTop1, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_BTNStartMenuTop1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageBTNStartMenu1 = lv_img_create(ui_BTNStartMenuTop1);
    lv_img_set_src(ui_ImageBTNStartMenu1, &ui_img_2126067643);
    lv_obj_set_width(ui_ImageBTNStartMenu1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageBTNStartMenu1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ImageBTNStartMenu1, 0);
    lv_obj_set_y(ui_ImageBTNStartMenu1, 1);
    lv_obj_set_align(ui_ImageBTNStartMenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBTNStartMenu1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_ImageBTNStartMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBTNStartMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemperatureShow2 = lv_obj_create(ui_ScreenAutoContentPanel1);
    lv_obj_set_width(ui_ArcTemperatureShow2, 450);
    lv_obj_set_height(ui_ArcTemperatureShow2, 180);
    lv_obj_set_x(ui_ArcTemperatureShow2, -100);
    lv_obj_set_y(ui_ArcTemperatureShow2, -110);
    lv_obj_set_align(ui_ArcTemperatureShow2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTemperatureShow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArcTemperatureShow2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperatureShow2, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcTemperatureShow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ArcTemperatureShow2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ArcTemperatureShow2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature3 = lv_label_create(ui_ArcTemperatureShow2);
    lv_obj_set_width(ui_LabelSensorTemperature3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTemperature3, 0);
    lv_obj_set_y(ui_LabelSensorTemperature3, -5);
    lv_obj_set_align(ui_LabelSensorTemperature3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature3, _("Set Temp"));
    lv_label_set_recolor(ui_LabelSensorTemperature3, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature3, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelManualTargetTemperature = lv_label_create(ui_ArcTemperatureShow2);
    lv_obj_set_width(ui_LabelManualTargetTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelManualTargetTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelManualTargetTemperature, 5);
    lv_obj_set_y(ui_LabelManualTargetTemperature, -10);
    lv_obj_set_align(ui_LabelManualTargetTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelManualTargetTemperature, "350°F");
    lv_obj_set_style_text_color(ui_LabelManualTargetTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelManualTargetTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelManualTargetTemperature, &ui_font_Montserrat_64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderManualTargetTemperature = lv_slider_create(ui_ArcTemperatureShow2);
    lv_slider_set_range(ui_SliderManualTargetTemperature, 212, 464);
    lv_slider_set_value(ui_SliderManualTargetTemperature, 350, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderManualTargetTemperature) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderManualTargetTemperature, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderManualTargetTemperature, 35);
    lv_obj_set_width(ui_SliderManualTargetTemperature, lv_pct(100));
    lv_obj_set_align(ui_SliderManualTargetTemperature, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_SliderManualTargetTemperature, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderManualTargetTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderManualTargetTemperature, lv_color_hex(0x191D26),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderManualTargetTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderManualTargetTemperature, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderManualTargetTemperature, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderManualTargetTemperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderManualTargetTemperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderManualTargetTemperature, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderManualTargetTemperature, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderManualTargetTemperature, lv_color_hex(0x1DE8FF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderManualTargetTemperature, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderManualTargetTemperature, lv_color_hex(0x0962B7),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderManualTargetTemperature, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderManualTargetTemperature, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderManualTargetTemperature, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderManualTargetTemperature, lv_color_hex(0x556483),
                                   LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderManualTargetTemperature, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderManualTargetTemperature, lv_color_hex(0x28DCFD),
                                  LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderManualTargetTemperature, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderManualTargetTemperature, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderManualTargetTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderManualTargetTemperature, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderManualTargetTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderManualTargetTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderManualTargetTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderManualTargetTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderManualTargetTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcTemperatureShow1 = lv_obj_create(ui_ScreenAutoContentPanel1);
    lv_obj_set_width(ui_ArcTemperatureShow1, 450);
    lv_obj_set_height(ui_ArcTemperatureShow1, 180);
    lv_obj_set_x(ui_ArcTemperatureShow1, -101);
    lv_obj_set_y(ui_ArcTemperatureShow1, -26);
    lv_obj_set_align(ui_ArcTemperatureShow1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ArcTemperatureShow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArcTemperatureShow1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperatureShow1, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcTemperatureShow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ArcTemperatureShow1, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ArcTemperatureShow1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature1 = lv_label_create(ui_ArcTemperatureShow1);
    lv_obj_set_width(ui_LabelSensorTemperature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTemperature1, 0);
    lv_obj_set_y(ui_LabelSensorTemperature1, -5);
    lv_obj_set_align(ui_LabelSensorTemperature1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature1, _("Set Countdown"));
    lv_label_set_recolor(ui_LabelSensorTemperature1, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature1, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelManualTimerSet = lv_label_create(ui_ArcTemperatureShow1);
    lv_obj_set_width(ui_LabelManualTimerSet, lv_pct(100));
    lv_obj_set_height(ui_LabelManualTimerSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelManualTimerSet, 5);
    lv_obj_set_y(ui_LabelManualTimerSet, -10);
    lv_obj_set_align(ui_LabelManualTimerSet, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelManualTimerSet, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelManualTimerSet, "Continuous Heat");
    lv_obj_set_style_text_color(ui_LabelManualTimerSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelManualTimerSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelManualTimerSet, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelManualTimerSet, &ui_font_Chinese_48_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarManualTemperature1 = lv_slider_create(ui_ArcTemperatureShow1);
    lv_slider_set_range(ui_BarManualTemperature1, 0, 90);
    lv_slider_set_value(ui_BarManualTemperature1, 18, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BarManualTemperature1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_BarManualTemperature1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_BarManualTemperature1, 35);
    lv_obj_set_width(ui_BarManualTemperature1, lv_pct(100));
    lv_obj_set_align(ui_BarManualTemperature1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_BarManualTemperature1, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarManualTemperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarManualTemperature1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarManualTemperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarManualTemperature1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarManualTemperature1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarManualTemperature1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarManualTemperature1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarManualTemperature1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarManualTemperature1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarManualTemperature1, lv_color_hex(0x1DE8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarManualTemperature1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarManualTemperature1, lv_color_hex(0x0962B7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarManualTemperature1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarManualTemperature1, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarManualTemperature1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarManualTemperature1, lv_color_hex(0x556483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarManualTemperature1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BarManualTemperature1, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BarManualTemperature1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BarManualTemperature1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BarManualTemperature1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BarManualTemperature1, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BarManualTemperature1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarManualTemperature1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarManualTemperature1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarManualTemperature1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarManualTemperature1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DropdownMotorLeftRightManual = lv_dropdown_create(ui_ScreenAutoContentPanel1);
    lv_dropdown_set_options(ui_DropdownMotorLeftRightManual, "Left\nRight\nBoth");
    lv_obj_set_width(ui_DropdownMotorLeftRightManual, 90);
    lv_obj_set_height(ui_DropdownMotorLeftRightManual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownMotorLeftRightManual, -262);
    lv_obj_set_y(ui_DropdownMotorLeftRightManual, -117);
    lv_obj_set_align(ui_DropdownMotorLeftRightManual, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_DropdownMotorLeftRightManual, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_flag(ui_DropdownMotorLeftRightManual, LV_OBJ_FLAG_HIDDEN);     /// Flags  

    lv_obj_add_event_cb(ui_BTNAutoMenuMove1, ui_event_BTNAutoMenuMove1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuSetting1, ui_event_BTNAutoMenuSetting1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNStartMenuTop1, ui_event_BTNStartMenuTop1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderManualTargetTemperature, ui_event_SliderManualTargetTemperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BarManualTemperature1, ui_event_BarManualTemperature1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownMotorLeftRightManual, ui_event_DropdownMotorLeftRightManual, LV_EVENT_ALL, NULL);

}
