// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenMenuConfigCreateMenu_screen_init(void)
{
    ui_ScreenMenuConfigCreateMenu = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenMenuConfigCreateMenu, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenuConfigCreateMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background3 = lv_img_create(ui_ScreenMenuConfigCreateMenu);
    lv_img_set_src(ui_Background3, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_Background3, 800);
    lv_obj_set_height(ui_Background3, 480);
    lv_obj_set_align(ui_Background3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNAutoMenuPrint4 = lv_img_create(ui_ScreenMenuConfigCreateMenu);
    lv_img_set_src(ui_BTNAutoMenuPrint4, &ui_img_photoshoped_assets_manual_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint4, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint4, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove4 = lv_img_create(ui_ScreenMenuConfigCreateMenu);
    lv_img_set_src(ui_BTNAutoMenuMove4, &ui_img_photoshoped_assets_timer_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuMove4, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove4, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuMove4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuSetting4 = lv_img_create(ui_ScreenMenuConfigCreateMenu);
    lv_img_set_src(ui_BTNAutoMenuSetting4, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting4, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting4, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header3 = lv_obj_create(ui_ScreenMenuConfigCreateMenu);
    lv_obj_set_width(ui_Panel_Header3, 665);
    lv_obj_set_height(ui_Panel_Header3, 39);
    lv_obj_set_x(ui_Panel_Header3, -30);
    lv_obj_set_y(ui_Panel_Header3, 0);
    lv_obj_set_align(ui_Panel_Header3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header3 = lv_label_create(ui_Panel_Header3);
    lv_obj_set_width(ui_Label_Header3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header3, _("User Menu: Create"));
    lv_label_set_recolor(ui_Label_Header3, "true");
    lv_obj_set_style_text_color(ui_Label_Header3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header3, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenAutoContentPanel2 = lv_obj_create(ui_ScreenMenuConfigCreateMenu);
    lv_obj_set_width(ui_ScreenAutoContentPanel2, 720);
    lv_obj_set_height(ui_ScreenAutoContentPanel2, 430);
    lv_obj_set_align(ui_ScreenAutoContentPanel2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ScreenAutoContentPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAutoContentPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenAutoContentPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenAutoContentPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRollerCreateMenuChoose = lv_obj_create(ui_ScreenAutoContentPanel2);
    lv_obj_set_height(ui_PanelRollerCreateMenuChoose, 215);
    lv_obj_set_width(ui_PanelRollerCreateMenuChoose, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_PanelRollerCreateMenuChoose, -30);
    lv_obj_set_y(ui_PanelRollerCreateMenuChoose, 15);
    lv_obj_set_align(ui_PanelRollerCreateMenuChoose, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PanelRollerCreateMenuChoose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRollerCreateMenuChoose, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelRollerCreateMenuChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRollerCreateMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCreateMenuText = lv_label_create(ui_PanelRollerCreateMenuChoose);
    lv_obj_set_width(ui_LabelCreateMenuText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCreateMenuText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCreateMenuText, -1);
    lv_obj_set_y(ui_LabelCreateMenuText, 7);
    lv_obj_set_align(ui_LabelCreateMenuText, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelCreateMenuText, _("Choose Menu"));
    lv_obj_set_style_text_color(ui_LabelCreateMenuText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCreateMenuText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelCreateMenuText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCreateMenuText, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownCreateMenuChoose = lv_dropdown_create(ui_PanelRollerCreateMenuChoose);
    lv_dropdown_set_options(ui_DropdownCreateMenuChoose,
                            "炸春捲\n炸雲吞\n炸餛飩\n炸魚\n炸蝦\n炸排骨\n炸花生\n炸蟹黃角\n炸豆腐\n炸雞翅中\n炸雞腿\n炸豆干\n炸薯條\n炸蘑菇\n炸茄盒\n炸豆皮卷\n炸脆皮腸\n炸海帶絲\n炸雞米花\n薯條\n洋蔥圈\n雞翅\n炸雞\n炸蝦\n芝士棒\n炸魚\n炸魷魚\n玉米狗\n土豆塊\n天婦羅\n雞條\n玉米球\n炸秋葵\n炸蘑菇\n炸蛤蜊\n炸牡蠣\n炸番茄\n炸春捲\n煎餃\n雞塊\n炸鯰魚\n炸魷魚\n油條");
    lv_obj_set_width(ui_DropdownCreateMenuChoose, 190);
    lv_obj_set_height(ui_DropdownCreateMenuChoose, 70);
    lv_obj_set_align(ui_DropdownCreateMenuChoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCreateMenuChoose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownCreateMenuChoose, &ui_font_Chinese_30_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownCreateMenuChoose, &lv_font_montserrat_30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownCreateMenuChoose), &ui_font_Chinese_30_Bold,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCreateMenuButton = lv_obj_create(ui_ScreenAutoContentPanel2);
    lv_obj_set_width(ui_PanelCreateMenuButton, 180);
    lv_obj_set_height(ui_PanelCreateMenuButton, 180);
    lv_obj_set_x(ui_PanelCreateMenuButton, -31);
    lv_obj_set_y(ui_PanelCreateMenuButton, -18);
    lv_obj_set_align(ui_PanelCreateMenuButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_PanelCreateMenuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCreateMenuButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelCreateMenuButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelCreateMenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNCreateMenu = lv_img_create(ui_PanelCreateMenuButton);
    lv_img_set_src(ui_BTNCreateMenu, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTNCreateMenu, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNCreateMenu, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNCreateMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNCreateMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNCreateMenuTop = lv_img_create(ui_BTNCreateMenu);
    lv_img_set_src(ui_BTNCreateMenuTop, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTNCreateMenuTop, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNCreateMenuTop, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNCreateMenuTop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNCreateMenuTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTNCreateMenuTop, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTNCreateMenuTop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTNCreateMenuTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNCreateMenuTop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTNCreateMenuTop, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTNCreateMenuTop, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTNCreateMenuTop, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_BTNCreateMenuTop, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_BTNCreateMenuTop, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTNCreateMenuTop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNCreateMenuTop, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNCreateMenuTop, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNCreateMenuTop, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_BTNCreateMenuTop, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_BTNCreateMenuTop, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageBTNCreateMenu = lv_img_create(ui_BTNCreateMenuTop);
    lv_img_set_src(ui_ImageBTNCreateMenu, &ui_img_984416508);
    lv_obj_set_width(ui_ImageBTNCreateMenu, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageBTNCreateMenu, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ImageBTNCreateMenu, 0);
    lv_obj_set_y(ui_ImageBTNCreateMenu, 1);
    lv_obj_set_align(ui_ImageBTNCreateMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBTNCreateMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_ImageBTNCreateMenu, 200);
    lv_obj_set_style_img_recolor(ui_ImageBTNCreateMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBTNCreateMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemperatureShow3 = lv_obj_create(ui_ScreenAutoContentPanel2);
    lv_obj_set_width(ui_ArcTemperatureShow3, 450);
    lv_obj_set_height(ui_ArcTemperatureShow3, 180);
    lv_obj_set_x(ui_ArcTemperatureShow3, -100);
    lv_obj_set_y(ui_ArcTemperatureShow3, -110);
    lv_obj_set_align(ui_ArcTemperatureShow3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTemperatureShow3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArcTemperatureShow3, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperatureShow3, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcTemperatureShow3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ArcTemperatureShow3, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ArcTemperatureShow3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderCreateMenuTargetTemp = lv_slider_create(ui_ArcTemperatureShow3);
    lv_slider_set_range(ui_SliderCreateMenuTargetTemp, 200, 400);
    lv_slider_set_value(ui_SliderCreateMenuTargetTemp, 350, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderCreateMenuTargetTemp) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderCreateMenuTargetTemp, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderCreateMenuTargetTemp, 35);
    lv_obj_set_width(ui_SliderCreateMenuTargetTemp, lv_pct(100));
    lv_obj_set_align(ui_SliderCreateMenuTargetTemp, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCreateMenuTargetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderCreateMenuTargetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderCreateMenuTargetTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderCreateMenuTargetTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderCreateMenuTargetTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderCreateMenuTargetTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderCreateMenuTargetTemp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderCreateMenuTargetTemp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x1DE8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCreateMenuTargetTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x0962B7),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderCreateMenuTargetTemp, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCreateMenuTargetTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x556483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderCreateMenuTargetTemp, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderCreateMenuTargetTemp, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderCreateMenuTargetTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderCreateMenuTargetTemp, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderCreateMenuTargetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderCreateMenuTargetTemp, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderCreateMenuTargetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderCreateMenuTargetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderCreateMenuTargetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderCreateMenuTargetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderCreateMenuTargetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MenuOptionRoller3 = lv_obj_create(ui_ArcTemperatureShow3);
    lv_obj_set_width(ui_MenuOptionRoller3, lv_pct(70));
    lv_obj_set_height(ui_MenuOptionRoller3, lv_pct(70));
    lv_obj_set_align(ui_MenuOptionRoller3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_MenuOptionRoller3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuOptionRoller3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuOptionRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuOptionRoller3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuOptionRoller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MenuOptionRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MenuOptionRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuOptionRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuOptionRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuOptionRoller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature9 = lv_label_create(ui_MenuOptionRoller3);
    lv_obj_set_width(ui_LabelSensorTemperature9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensorTemperature9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature9, _("Set Temp"));
    lv_label_set_recolor(ui_LabelSensorTemperature9, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature9, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensorTemperature9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature9, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCreateMenuTargetTemperature = lv_label_create(ui_MenuOptionRoller3);
    lv_obj_set_width(ui_LabelCreateMenuTargetTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCreateMenuTargetTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCreateMenuTargetTemperature, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelCreateMenuTargetTemperature, "350°F");
    lv_obj_set_style_text_color(ui_LabelCreateMenuTargetTemperature, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCreateMenuTargetTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCreateMenuTargetTemperature, &ui_font_Montserrat_64,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemperatureShow4 = lv_obj_create(ui_ScreenAutoContentPanel2);
    lv_obj_set_width(ui_ArcTemperatureShow4, 450);
    lv_obj_set_height(ui_ArcTemperatureShow4, 180);
    lv_obj_set_x(ui_ArcTemperatureShow4, -101);
    lv_obj_set_y(ui_ArcTemperatureShow4, -26);
    lv_obj_set_align(ui_ArcTemperatureShow4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ArcTemperatureShow4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArcTemperatureShow4, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperatureShow4, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcTemperatureShow4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ArcTemperatureShow4, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ArcTemperatureShow4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderCreateMenuTargetCountdown = lv_slider_create(ui_ArcTemperatureShow4);
    lv_slider_set_range(ui_SliderCreateMenuTargetCountdown, 0, 90);
    lv_slider_set_value(ui_SliderCreateMenuTargetCountdown, 18, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderCreateMenuTargetCountdown) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderCreateMenuTargetCountdown, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderCreateMenuTargetCountdown, 35);
    lv_obj_set_width(ui_SliderCreateMenuTargetCountdown, lv_pct(100));
    lv_obj_set_align(ui_SliderCreateMenuTargetCountdown, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCreateMenuTargetCountdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x191D26),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderCreateMenuTargetCountdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderCreateMenuTargetCountdown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderCreateMenuTargetCountdown, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderCreateMenuTargetCountdown, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderCreateMenuTargetCountdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderCreateMenuTargetCountdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x1DE8FF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCreateMenuTargetCountdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x0962B7),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderCreateMenuTargetCountdown, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCreateMenuTargetCountdown, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x556483),
                                   LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderCreateMenuTargetCountdown, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderCreateMenuTargetCountdown, lv_color_hex(0x28DCFD),
                                  LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderCreateMenuTargetCountdown, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderCreateMenuTargetCountdown, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderCreateMenuTargetCountdown, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderCreateMenuTargetCountdown, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelCreateMenuCountdownText = lv_label_create(ui_ArcTemperatureShow4);
    lv_obj_set_width(ui_LabelCreateMenuCountdownText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCreateMenuCountdownText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCreateMenuCountdownText, 0);
    lv_obj_set_y(ui_LabelCreateMenuCountdownText, -5);
    lv_obj_set_align(ui_LabelCreateMenuCountdownText, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelCreateMenuCountdownText, _("Set Countdown"));
    lv_label_set_recolor(ui_LabelCreateMenuCountdownText, "true");
    lv_obj_set_style_text_color(ui_LabelCreateMenuCountdownText, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCreateMenuCountdownText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCreateMenuCountdownText, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCreateMenuCountdown = lv_label_create(ui_ArcTemperatureShow4);
    lv_obj_set_width(ui_LabelCreateMenuCountdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCreateMenuCountdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCreateMenuCountdown, 0);
    lv_obj_set_y(ui_LabelCreateMenuCountdown, -10);
    lv_obj_set_align(ui_LabelCreateMenuCountdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCreateMenuCountdown, "03:00");
    lv_label_set_recolor(ui_LabelCreateMenuCountdown, "true");
    lv_obj_set_style_text_color(ui_LabelCreateMenuCountdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCreateMenuCountdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCreateMenuCountdown, &ui_font_Montserrat_64, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTNAutoMenuPrint4, ui_event_BTNAutoMenuPrint4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuMove4, ui_event_BTNAutoMenuMove4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNCreateMenuTop, ui_event_BTNCreateMenuTop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderCreateMenuTargetTemp, ui_event_SliderCreateMenuTargetTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderCreateMenuTargetCountdown, ui_event_SliderCreateMenuTargetCountdown, LV_EVENT_ALL, NULL);

}
