// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenScreenSaverMenu_screen_init(void)
{
    ui_ScreenScreenSaverMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenScreenSaverMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMenu = lv_obj_create(ui_ScreenScreenSaverMenu);
    lv_obj_set_width(ui_PanelMenu, lv_pct(100));
    lv_obj_set_height(ui_PanelMenu, lv_pct(100));
    lv_obj_set_align(ui_PanelMenu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMenuName = lv_label_create(ui_PanelMenu);
    lv_obj_set_width(ui_LabelMenuName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMenuName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMenuName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenuName, _("menu_name"));
    lv_obj_set_style_text_font(ui_LabelMenuName, &ui_font_Chinese_70_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressAnywhereToExit = lv_label_create(ui_PanelMenu);
    lv_obj_set_width(ui_LabelPressAnywhereToExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPressAnywhereToExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPressAnywhereToExit, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelPressAnywhereToExit, _("Press anywhere or any button to exit"));
    lv_obj_set_style_text_font(ui_LabelPressAnywhereToExit, &ui_font_Chinese_30_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_PanelMenu);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(30));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenSaverLeftPanel = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_ScreenSaverLeftPanel, lv_pct(50));
    lv_obj_set_height(ui_ScreenSaverLeftPanel, lv_pct(100));
    lv_obj_set_align(ui_ScreenSaverLeftPanel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ScreenSaverLeftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSaverLeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenSaverLeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenSaverCookingState = lv_label_create(ui_ScreenSaverLeftPanel);
    lv_obj_set_width(ui_LabelScreenSaverCookingState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenSaverCookingState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenSaverCookingState, 0);
    lv_obj_set_y(ui_LabelScreenSaverCookingState, lv_pct(10));
    lv_obj_set_align(ui_LabelScreenSaverCookingState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenSaverCookingState, _("State"));
    lv_obj_set_style_text_font(ui_LabelScreenSaverCookingState, &ui_font_Chinese_48_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenSaverRightPanel = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_ScreenSaverRightPanel, lv_pct(50));
    lv_obj_set_height(ui_ScreenSaverRightPanel, lv_pct(100));
    lv_obj_set_align(ui_ScreenSaverRightPanel, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ScreenSaverRightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSaverRightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenSaverRightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenSaverCookingCountdown = lv_label_create(ui_ScreenSaverRightPanel);
    lv_obj_set_width(ui_LabelScreenSaverCookingCountdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenSaverCookingCountdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenSaverCookingCountdown, 0);
    lv_obj_set_y(ui_LabelScreenSaverCookingCountdown, lv_pct(10));
    lv_obj_set_align(ui_LabelScreenSaverCookingCountdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenSaverCookingCountdown, _("Countdown"));
    lv_obj_set_style_text_font(ui_LabelScreenSaverCookingCountdown, &ui_font_Chinese_48_Bold,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splitter2 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Splitter2, 3);
    lv_obj_set_height(ui_Splitter2, lv_pct(80));
    lv_obj_set_align(ui_Splitter2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Splitter2, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splitter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Splitter2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Splitter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Splitter2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelMenu, ui_event_PanelMenu, LV_EVENT_ALL, NULL);

}
