// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenMenuConfigDeleteMenu_screen_init(void)
{
    ui_ScreenMenuConfigDeleteMenu = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenMenuConfigDeleteMenu, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenuConfigDeleteMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background4 = lv_img_create(ui_ScreenMenuConfigDeleteMenu);
    lv_img_set_src(ui_Background4, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_Background4, 800);
    lv_obj_set_height(ui_Background4, 480);
    lv_obj_set_align(ui_Background4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNAutoMenuPrint5 = lv_img_create(ui_ScreenMenuConfigDeleteMenu);
    lv_img_set_src(ui_BTNAutoMenuPrint5, &ui_img_photoshoped_assets_manual_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint5, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint5, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove5 = lv_img_create(ui_ScreenMenuConfigDeleteMenu);
    lv_img_set_src(ui_BTNAutoMenuMove5, &ui_img_photoshoped_assets_timer_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuMove5, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove5, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuMove5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuSetting5 = lv_img_create(ui_ScreenMenuConfigDeleteMenu);
    lv_img_set_src(ui_BTNAutoMenuSetting5, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting5, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting5, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header4 = lv_obj_create(ui_ScreenMenuConfigDeleteMenu);
    lv_obj_set_width(ui_Panel_Header4, 665);
    lv_obj_set_height(ui_Panel_Header4, 39);
    lv_obj_set_x(ui_Panel_Header4, -30);
    lv_obj_set_y(ui_Panel_Header4, 0);
    lv_obj_set_align(ui_Panel_Header4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header4 = lv_label_create(ui_Panel_Header4);
    lv_obj_set_width(ui_Label_Header4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header4, _("User Menu: Delete"));
    lv_label_set_recolor(ui_Label_Header4, "true");
    lv_obj_set_style_text_color(ui_Label_Header4, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header4, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenMenuConfigDelMenu = lv_obj_create(ui_ScreenMenuConfigDeleteMenu);
    lv_obj_set_width(ui_ScreenMenuConfigDelMenu, 720);
    lv_obj_set_height(ui_ScreenMenuConfigDelMenu, 430);
    lv_obj_set_align(ui_ScreenMenuConfigDelMenu, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ScreenMenuConfigDelMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMenuConfigDelMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenMenuConfigDelMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenMenuConfigDelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRollerDeleteMenuChoose = lv_obj_create(ui_ScreenMenuConfigDelMenu);
    lv_obj_set_height(ui_PanelRollerDeleteMenuChoose, 215);
    lv_obj_set_width(ui_PanelRollerDeleteMenuChoose, LV_SIZE_CONTENT);   /// 165
    lv_obj_set_x(ui_PanelRollerDeleteMenuChoose, 100);
    lv_obj_set_y(ui_PanelRollerDeleteMenuChoose, -9);
    lv_obj_set_align(ui_PanelRollerDeleteMenuChoose, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelRollerDeleteMenuChoose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRollerDeleteMenuChoose, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelRollerDeleteMenuChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMGRollerDeleteMenuChoose = lv_img_create(ui_PanelRollerDeleteMenuChoose);
    lv_img_set_src(ui_IMGRollerDeleteMenuChoose, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_IMGRollerDeleteMenuChoose, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMGRollerDeleteMenuChoose, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMGRollerDeleteMenuChoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGRollerDeleteMenuChoose, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_RollerDeleteMenuChoose = lv_roller_create(ui_PanelRollerDeleteMenuChoose);
    lv_roller_set_options(ui_RollerDeleteMenuChoose,
                          "炸春卷\n炸雲吞\n炸餛飩\n炸魚\n炸蝦\n炸排骨\n炸花生\n炸蟹黃角\n炸豆腐\n炸雞翅中\n炸雞腿\n炸豆干\n炸薯條\n炸蘑菇\n炸茄盒\n炸豆皮卷\n炸脆皮腸\n炸海帶絲\n炸雞米花\n薯條\n洋蔥圈\n雞翅\n炸雞\n炸蝦\n芝士棒\n炸魚\n炸魷魚\n玉米狗\n土豆塊\n天婦羅\n雞條\n玉米球\n炸秋葵\n炸蘑菇\n炸蛤蜊\n炸牡蠣\n炸番茄\n炸春捲\n煎餃\n雞塊\n炸鯰魚\n炸魷魚\n油條",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerDeleteMenuChoose, 141);
    lv_obj_set_height(ui_RollerDeleteMenuChoose, 131);
    lv_obj_set_align(ui_RollerDeleteMenuChoose, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerDeleteMenuChoose, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerDeleteMenuChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerDeleteMenuChoose, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerDeleteMenuChoose, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RollerDeleteMenuChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerDeleteMenuChoose, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerDeleteMenuChoose, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerDeleteMenuChoose, &ui_font_Chinese_30_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerDeleteMenuChoose, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerDeleteMenuChoose, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PanelRollerDeleteMenuChooseBTN = lv_obj_create(ui_ScreenMenuConfigDelMenu);
    lv_obj_set_width(ui_PanelRollerDeleteMenuChooseBTN, 180);
    lv_obj_set_height(ui_PanelRollerDeleteMenuChooseBTN, 180);
    lv_obj_set_x(ui_PanelRollerDeleteMenuChooseBTN, 150);
    lv_obj_set_y(ui_PanelRollerDeleteMenuChooseBTN, 0);
    lv_obj_set_align(ui_PanelRollerDeleteMenuChooseBTN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRollerDeleteMenuChooseBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRollerDeleteMenuChooseBTN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelRollerDeleteMenuChooseBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRollerDeleteMenuChooseBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNDeleteMenuChoose = lv_img_create(ui_PanelRollerDeleteMenuChooseBTN);
    lv_img_set_src(ui_BTNDeleteMenuChoose, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTNDeleteMenuChoose, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNDeleteMenuChoose, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNDeleteMenuChoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNDeleteMenuChoose, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNDeleteMenuChooseTop = lv_img_create(ui_BTNDeleteMenuChoose);
    lv_img_set_src(ui_BTNDeleteMenuChooseTop, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTNDeleteMenuChooseTop, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNDeleteMenuChooseTop, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNDeleteMenuChooseTop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNDeleteMenuChooseTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTNDeleteMenuChooseTop, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTNDeleteMenuChooseTop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTNDeleteMenuChooseTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNDeleteMenuChooseTop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTNDeleteMenuChooseTop, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTNDeleteMenuChooseTop, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTNDeleteMenuChooseTop, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_BTNDeleteMenuChooseTop, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_BTNDeleteMenuChooseTop, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTNDeleteMenuChooseTop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNDeleteMenuChooseTop, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNDeleteMenuChooseTop, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNDeleteMenuChooseTop, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_BTNDeleteMenuChooseTop, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_BTNDeleteMenuChooseTop, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageBTNDeleteMenuChoose = lv_img_create(ui_BTNDeleteMenuChooseTop);
    lv_img_set_src(ui_ImageBTNDeleteMenuChoose, &ui_img_821558544);
    lv_obj_set_width(ui_ImageBTNDeleteMenuChoose, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageBTNDeleteMenuChoose, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ImageBTNDeleteMenuChoose, 0);
    lv_obj_set_y(ui_ImageBTNDeleteMenuChoose, 1);
    lv_obj_set_align(ui_ImageBTNDeleteMenuChoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBTNDeleteMenuChoose, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_ImageBTNDeleteMenuChoose, 200);
    lv_obj_set_style_img_recolor(ui_ImageBTNDeleteMenuChoose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBTNDeleteMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTNAutoMenuPrint5, ui_event_BTNAutoMenuPrint5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuMove5, ui_event_BTNAutoMenuMove5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerDeleteMenuChoose, ui_event_RollerDeleteMenuChoose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNDeleteMenuChooseTop, ui_event_BTNDeleteMenuChooseTop, LV_EVENT_ALL, NULL);

}
