// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenAuto_screen_init(void)
{
    ui_ScreenAuto = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenAuto, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAuto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenAutoBackgroundPicture = lv_img_create(ui_ScreenAuto);
    lv_img_set_src(ui_ScreenAutoBackgroundPicture, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_ScreenAutoBackgroundPicture, 800);
    lv_obj_set_height(ui_ScreenAutoBackgroundPicture, 480);
    lv_obj_set_align(ui_ScreenAutoBackgroundPicture, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenAutoBackgroundPicture, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_ScreenAutoHeader = lv_obj_create(ui_ScreenAuto);
    lv_obj_set_width(ui_ScreenAutoHeader, 665);
    lv_obj_set_height(ui_ScreenAutoHeader, 39);
    lv_obj_set_x(ui_ScreenAutoHeader, -30);
    lv_obj_set_y(ui_ScreenAutoHeader, 0);
    lv_obj_set_align(ui_ScreenAutoHeader, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ScreenAutoHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAutoHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAutoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenAutoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenAutoHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenAutoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAutoHeader = lv_label_create(ui_ScreenAutoHeader);
    lv_obj_set_width(ui_LabelAutoHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAutoHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAutoHeader, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelAutoHeader, _("Scroll to choose menu, Press to Start"));
    lv_label_set_recolor(ui_LabelAutoHeader, "true");
    lv_obj_set_style_text_color(ui_LabelAutoHeader, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAutoHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAutoHeader, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeaderVersionNumber1 = lv_label_create(ui_ScreenAutoHeader);
    lv_obj_set_width(ui_LabelHeaderVersionNumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeaderVersionNumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHeaderVersionNumber1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelHeaderVersionNumber1, "version");
    lv_label_set_recolor(ui_LabelHeaderVersionNumber1, "true");
    lv_obj_set_style_text_color(ui_LabelHeaderVersionNumber1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeaderVersionNumber1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeaderVersionNumber1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuPrint = lv_img_create(ui_ScreenAuto);
    lv_img_set_src(ui_BTNAutoMenuPrint, &ui_img_photoshoped_assets_chinese_manual_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove = lv_img_create(ui_ScreenAuto);
    lv_img_set_src(ui_BTNAutoMenuMove, &ui_img_photoshoped_assets_chinese_timer_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuMove, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTNAutoMenuSetting = lv_img_create(ui_ScreenAuto);
    lv_img_set_src(ui_BTNAutoMenuSetting, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenAutoContentPanel = lv_obj_create(ui_ScreenAuto);
    lv_obj_set_width(ui_ScreenAutoContentPanel, 720);
    lv_obj_set_height(ui_ScreenAutoContentPanel, 430);
    lv_obj_set_align(ui_ScreenAutoContentPanel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ScreenAutoContentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAutoContentPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenAutoContentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenAutoContentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplayTempRemainCountdown = lv_obj_create(ui_ScreenAutoContentPanel);
    lv_obj_set_width(ui_DisplayTempRemainCountdown, 450);
    lv_obj_set_height(ui_DisplayTempRemainCountdown, 125);
    lv_obj_set_x(ui_DisplayTempRemainCountdown, 33);
    lv_obj_set_y(ui_DisplayTempRemainCountdown, -43);
    lv_obj_set_align(ui_DisplayTempRemainCountdown, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_DisplayTempRemainCountdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DisplayTempRemainCountdown, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplayTempRemainCountdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DisplayTempRemainCountdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DisplayTempRemainCountdown, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DisplayTempRemainCountdown, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DisplayTempRemainCountdown, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DisplayTempRemainCountdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DTRC0 = lv_obj_create(ui_DisplayTempRemainCountdown);
    lv_obj_set_width(ui_DTRC0, lv_pct(55));
    lv_obj_set_height(ui_DTRC0, lv_pct(100));
    lv_obj_set_align(ui_DTRC0, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_DTRC0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DTRC0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DTRC0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DTRC0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DTRC0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DTRC0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DTRC0, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DTRC0, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DTRC0, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DTRC0, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature = lv_label_create(ui_DTRC0);
    lv_obj_set_width(ui_LabelSensorTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensorTemperature, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature, _("Temp"));
    lv_label_set_recolor(ui_LabelSensorTemperature, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTempValue = lv_label_create(ui_DTRC0);
    lv_obj_set_width(ui_LabelSensorTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensorTempValue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSensorTempValue, "...");
    lv_obj_set_style_text_color(ui_LabelSensorTempValue, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTempValue, &ui_font_Montserrat_64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splitter1 = lv_obj_create(ui_DTRC0);
    lv_obj_set_width(ui_Splitter1, 2);
    lv_obj_set_height(ui_Splitter1, 50);
    lv_obj_set_x(ui_Splitter1, 6);
    lv_obj_set_y(ui_Splitter1, 0);
    lv_obj_set_align(ui_Splitter1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Splitter1, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splitter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Splitter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Splitter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Splitter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DTRC2 = lv_obj_create(ui_DisplayTempRemainCountdown);
    lv_obj_set_width(ui_DTRC2, lv_pct(43));
    lv_obj_set_height(ui_DTRC2, lv_pct(100));
    lv_obj_set_align(ui_DTRC2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_DTRC2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DTRC2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DTRC2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DTRC2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DTRC2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DTRC2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DTRC2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DTRC2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DTRC2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DTRC2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSetTime = lv_label_create(ui_DTRC2);
    lv_obj_set_width(ui_LabelSetTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSetTime, _("Countdown"));
    lv_label_set_recolor(ui_LabelSetTime, "true");
    lv_obj_set_style_text_color(ui_LabelSetTime, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSetTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetTime, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSetTimeValue = lv_label_create(ui_DTRC2);
    lv_obj_set_width(ui_LabelSetTimeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetTimeValue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSetTimeValue, _("Heat"));
    lv_obj_set_style_text_color(ui_LabelSetTimeValue, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSetTimeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetTimeValue, &ui_font_Chinese_60_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Buttons_S3 = lv_obj_create(ui_ScreenAutoContentPanel);
    lv_obj_set_width(ui_Panel_Buttons_S3, 180);
    lv_obj_set_height(ui_Panel_Buttons_S3, 180);
    lv_obj_set_x(ui_Panel_Buttons_S3, -31);
    lv_obj_set_y(ui_Panel_Buttons_S3, -18);
    lv_obj_set_align(ui_Panel_Buttons_S3, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Panel_Buttons_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Buttons_S3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Buttons_S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Buttons_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNStartMenu = lv_img_create(ui_Panel_Buttons_S3);
    lv_img_set_src(ui_BTNStartMenu, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTNStartMenu, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNStartMenu, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNStartMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNStartMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNStartMenuTop = lv_img_create(ui_BTNStartMenu);
    lv_img_set_src(ui_BTNStartMenuTop, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTNStartMenuTop, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNStartMenuTop, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNStartMenuTop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNStartMenuTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTNStartMenuTop, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTNStartMenuTop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTNStartMenuTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNStartMenuTop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTNStartMenuTop, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTNStartMenuTop, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTNStartMenuTop, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_BTNStartMenuTop, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_BTNStartMenuTop, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTNStartMenuTop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNStartMenuTop, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNStartMenuTop, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNStartMenuTop, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_BTNStartMenuTop, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_BTNStartMenuTop, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageBTNStartMenu = lv_img_create(ui_BTNStartMenuTop);
    lv_img_set_src(ui_ImageBTNStartMenu, &ui_img_2126067643);
    lv_obj_set_width(ui_ImageBTNStartMenu, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageBTNStartMenu, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ImageBTNStartMenu, 0);
    lv_obj_set_y(ui_ImageBTNStartMenu, 1);
    lv_obj_set_align(ui_ImageBTNStartMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBTNStartMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_ImageBTNStartMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBTNStartMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuOptionRoller = lv_obj_create(ui_ScreenAutoContentPanel);
    lv_obj_set_height(ui_MenuOptionRoller, 215);
    lv_obj_set_width(ui_MenuOptionRoller, LV_SIZE_CONTENT);   /// 165
    lv_obj_set_x(ui_MenuOptionRoller, -32);
    lv_obj_set_y(ui_MenuOptionRoller, -9);
    lv_obj_set_align(ui_MenuOptionRoller, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_MenuOptionRoller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuOptionRoller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MenuOptionRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuOptionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMGMenuOptionRoller = lv_img_create(ui_MenuOptionRoller);
    lv_img_set_src(ui_IMGMenuOptionRoller, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_IMGMenuOptionRoller, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMGMenuOptionRoller, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMGMenuOptionRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGMenuOptionRoller, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_MenuOptionRollerChoose = lv_roller_create(ui_MenuOptionRoller);
    lv_roller_set_options(ui_MenuOptionRollerChoose, "鸡块\n牛排\n鸡翅\n汉堡", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_MenuOptionRollerChoose, 141);
    lv_obj_set_height(ui_MenuOptionRollerChoose, 131);
    lv_obj_set_align(ui_MenuOptionRollerChoose, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_MenuOptionRollerChoose, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuOptionRollerChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuOptionRollerChoose, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuOptionRollerChoose, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuOptionRollerChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MenuOptionRollerChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MenuOptionRollerChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MenuOptionRollerChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MenuOptionRollerChoose, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuOptionRollerChoose, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuOptionRollerChoose, &ui_font_Chinese_30_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuOptionRollerChoose, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuOptionRollerChoose, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ArcTemperatureShow = lv_obj_create(ui_ScreenAutoContentPanel);
    lv_obj_set_width(ui_ArcTemperatureShow, 450);
    lv_obj_set_height(ui_ArcTemperatureShow, 180);
    lv_obj_set_x(ui_ArcTemperatureShow, -100);
    lv_obj_set_y(ui_ArcTemperatureShow, -110);
    lv_obj_set_align(ui_ArcTemperatureShow, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTemperatureShow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArcTemperatureShow, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperatureShow, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcTemperatureShow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ArcTemperatureShow, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ArcTemperatureShow, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DTRC3 = lv_obj_create(ui_ArcTemperatureShow);
    lv_obj_set_width(ui_DTRC3, lv_pct(100));
    lv_obj_set_height(ui_DTRC3, lv_pct(100));
    lv_obj_set_x(ui_DTRC3, 10);
    lv_obj_set_y(ui_DTRC3, -15);
    lv_obj_set_align(ui_DTRC3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_DTRC3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DTRC3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DTRC3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DTRC3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DTRC3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DTRC3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DTRC3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DTRC3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DTRC3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DTRC3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensorTemperature2 = lv_label_create(ui_DTRC3);
    lv_obj_set_width(ui_LabelSensorTemperature2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorTemperature2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorTemperature2, -17);
    lv_obj_set_y(ui_LabelSensorTemperature2, 0);
    lv_obj_set_align(ui_LabelSensorTemperature2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSensorTemperature2, _("Set Temp"));
    lv_label_set_recolor(ui_LabelSensorTemperature2, "true");
    lv_obj_set_style_text_color(ui_LabelSensorTemperature2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensorTemperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensorTemperature2, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTargetTemperatureValue = lv_label_create(ui_DTRC3);
    lv_obj_set_width(ui_LabelTargetTemperatureValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTargetTemperatureValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTargetTemperatureValue, -10);
    lv_obj_set_y(ui_LabelTargetTemperatureValue, 6);
    lv_obj_set_align(ui_LabelTargetTemperatureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTargetTemperatureValue, "350°F");
    lv_obj_set_style_text_color(ui_LabelTargetTemperatureValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTargetTemperatureValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTargetTemperatureValue, &ui_font_Montserrat_64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarCountDownTemperature = lv_bar_create(ui_ArcTemperatureShow);
    lv_bar_set_range(ui_BarCountDownTemperature, 200, 400);
    lv_bar_set_value(ui_BarCountDownTemperature, 320, LV_ANIM_OFF);
    lv_obj_set_height(ui_BarCountDownTemperature, 35);
    lv_obj_set_width(ui_BarCountDownTemperature, lv_pct(100));
    lv_obj_set_align(ui_BarCountDownTemperature, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_BarCountDownTemperature, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarCountDownTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarCountDownTemperature, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarCountDownTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarCountDownTemperature, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarCountDownTemperature, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarCountDownTemperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarCountDownTemperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarCountDownTemperature, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarCountDownTemperature, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarCountDownTemperature, lv_color_hex(0x1DE8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarCountDownTemperature, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarCountDownTemperature, lv_color_hex(0x0962B7),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarCountDownTemperature, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_DropdownMotorLeftRightAuto = lv_dropdown_create(ui_ScreenAutoContentPanel);
    lv_dropdown_set_options(ui_DropdownMotorLeftRightAuto, "Left\nRight\nBoth");
    lv_obj_set_width(ui_DropdownMotorLeftRightAuto, 90);
    lv_obj_set_height(ui_DropdownMotorLeftRightAuto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownMotorLeftRightAuto, -262);
    lv_obj_set_y(ui_DropdownMotorLeftRightAuto, -117);
    lv_obj_set_align(ui_DropdownMotorLeftRightAuto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownMotorLeftRightAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_BTNAutoMenuPrint, ui_event_BTNAutoMenuPrint, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuSetting, ui_event_BTNAutoMenuSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNStartMenuTop, ui_event_BTNStartMenuTop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuOptionRollerChoose, ui_event_MenuOptionRollerChoose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownMotorLeftRightAuto, ui_event_DropdownMotorLeftRightAuto, LV_EVENT_ALL, NULL);

}
