// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenSetting_screen_init(void)
{
    ui_ScreenSetting = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenSetting, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background2 = lv_img_create(ui_ScreenSetting);
    lv_img_set_src(ui_Background2, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_Background2, 800);
    lv_obj_set_height(ui_Background2, 480);
    lv_obj_set_align(ui_Background2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNAutoMenuPrint2 = lv_img_create(ui_ScreenSetting);
    lv_img_set_src(ui_BTNAutoMenuPrint2, &ui_img_photoshoped_assets_manual_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint2, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint2, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove2 = lv_img_create(ui_ScreenSetting);
    lv_img_set_src(ui_BTNAutoMenuMove2, &ui_img_photoshoped_assets_timer_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuMove2, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove2, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuMove2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuSetting2 = lv_img_create(ui_ScreenSetting);
    lv_img_set_src(ui_BTNAutoMenuSetting2, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting2, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting2, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header2 = lv_obj_create(ui_ScreenSetting);
    lv_obj_set_width(ui_Panel_Header2, 665);
    lv_obj_set_height(ui_Panel_Header2, 39);
    lv_obj_set_x(ui_Panel_Header2, -30);
    lv_obj_set_y(ui_Panel_Header2, 0);
    lv_obj_set_align(ui_Panel_Header2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header2 = lv_label_create(ui_Panel_Header2);
    lv_obj_set_width(ui_Label_Header2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header2, _("Settings"));
    lv_label_set_recolor(ui_Label_Header2, "true");
    lv_obj_set_style_text_color(ui_Label_Header2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header2, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1_Content_Panel2 = lv_obj_create(ui_ScreenSetting);
    lv_obj_set_width(ui_S1_Content_Panel2, 720);
    lv_obj_set_height(ui_S1_Content_Panel2, 430);
    lv_obj_set_align(ui_S1_Content_Panel2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_S1_Content_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller_Material = lv_obj_create(ui_S1_Content_Panel2);
    lv_obj_set_height(ui_Roller_Material, 215);
    lv_obj_set_width(ui_Roller_Material, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_Roller_Material, 350);
    lv_obj_set_y(ui_Roller_Material, 20);
    lv_obj_clear_flag(ui_Roller_Material, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Roller_Material, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller_Material, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Roller_Material, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Roller_Material);
    lv_img_set_src(ui_Image3, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Roller4 = lv_roller_create(ui_Roller_Material);
    lv_roller_set_options(ui_Roller4, "15\n30\n45\n60\n75\n90\n105\n120", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller4, 141);
    lv_obj_set_height(ui_Roller4, 131);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Roller4, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_color(ui_Roller4, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller4, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller4, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller4, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller4, &ui_font_Chinese_30_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller4, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller4, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label_Material = lv_label_create(ui_Roller_Material);
    lv_obj_set_width(ui_Label_Material, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Material, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Material, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Material, _("Self Clean (min)"));
    lv_label_set_recolor(ui_Label_Material, "true");
    lv_obj_set_style_text_color(ui_Label_Material, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Material, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Material, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Material, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller_Bed_Temp = lv_obj_create(ui_S1_Content_Panel2);
    lv_obj_set_height(ui_Roller_Bed_Temp, 215);
    lv_obj_set_width(ui_Roller_Bed_Temp, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_Roller_Bed_Temp, 175);
    lv_obj_set_y(ui_Roller_Bed_Temp, 20);
    lv_obj_clear_flag(ui_Roller_Bed_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Roller_Bed_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller_Bed_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Roller_Bed_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Roller_Bed_Temp);
    lv_img_set_src(ui_Image2, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Roller3 = lv_roller_create(ui_Roller_Bed_Temp);
    lv_roller_set_options(ui_Roller3, "Normal\nEco\nPwr", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller3, 141);
    lv_obj_set_height(ui_Roller3, 131);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Roller3, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_color(ui_Roller3, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller3, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller3, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller3, &ui_font_Chinese_30_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label_Bed_Temp1 = lv_label_create(ui_Roller_Bed_Temp);
    lv_obj_set_width(ui_Label_Bed_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Bed_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Bed_Temp1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Bed_Temp1, _("Power Mode"));
    lv_label_set_recolor(ui_Label_Bed_Temp1, "true");
    lv_obj_set_style_text_color(ui_Label_Bed_Temp1, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Bed_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Bed_Temp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Bed_Temp1, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller_Head_Temp = lv_obj_create(ui_S1_Content_Panel2);
    lv_obj_set_height(ui_Roller_Head_Temp, 215);
    lv_obj_set_width(ui_Roller_Head_Temp, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_Roller_Head_Temp, 0);
    lv_obj_set_y(ui_Roller_Head_Temp, 20);
    lv_obj_clear_flag(ui_Roller_Head_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Roller_Head_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller_Head_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Roller_Head_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Roller_Head_Temp);
    lv_img_set_src(ui_Image1, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Roller2 = lv_roller_create(ui_Roller_Head_Temp);
    lv_roller_set_options(ui_Roller2, "English\n繁體中文\n简体中文\nEspañol\nFrançais\nIndonesian",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller2, 141);
    lv_obj_set_height(ui_Roller2, 131);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller2, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller2, &ui_font_Chinese_25_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label_Head_Temp1 = lv_label_create(ui_Roller_Head_Temp);
    lv_obj_set_width(ui_Label_Head_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Head_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Head_Temp1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Head_Temp1, _("Language"));
    lv_label_set_recolor(ui_Label_Head_Temp1, "true");
    lv_obj_set_style_text_color(ui_Label_Head_Temp1, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Head_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Head_Temp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Head_Temp1, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Heat_Head = lv_imgbtn_create(ui_S1_Content_Panel2);
    lv_imgbtn_set_src(ui_BTN_Heat_Head, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat_Head, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat_Head, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat_Head, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Heat_Head, 66);
    lv_obj_set_width(ui_BTN_Heat_Head, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Heat_Head, 12);
    lv_obj_set_y(ui_BTN_Heat_Head, 40);
    lv_obj_set_align(ui_BTN_Heat_Head, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Heat_Head, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Heat_Head, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Heat_Head, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Heat_Head, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Heat_Head, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Heat_Head, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Heat_Head, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Reset22 = lv_label_create(ui_BTN_Heat_Head);
    lv_obj_set_width(ui_Label_Reset22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Reset22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Reset22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Reset22, _("Menu"));
    lv_label_set_recolor(ui_Label_Reset22, "true");
    lv_obj_set_style_text_align(ui_Label_Reset22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Reset22, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Heat_Bed = lv_imgbtn_create(ui_S1_Content_Panel2);
    lv_imgbtn_set_src(ui_BTN_Heat_Bed, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat_Bed, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat_Bed, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat_Bed, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Heat_Bed, 66);
    lv_obj_set_width(ui_BTN_Heat_Bed, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Heat_Bed, 185);
    lv_obj_set_y(ui_BTN_Heat_Bed, 40);
    lv_obj_set_align(ui_BTN_Heat_Bed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Heat_Bed, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Heat_Bed, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Heat_Bed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Heat_Bed, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Heat_Bed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Heat_Bed, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Heat_Bed, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Heat_Bed = lv_label_create(ui_BTN_Heat_Bed);
    lv_obj_set_width(ui_Label_Heat_Bed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Heat_Bed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Heat_Bed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Heat_Bed, _("About"));
    lv_label_set_recolor(ui_Label_Heat_Bed, "true");
    lv_obj_set_style_text_align(ui_Label_Heat_Bed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Heat_Bed, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Remove_Filament = lv_imgbtn_create(ui_S1_Content_Panel2);
    lv_imgbtn_set_src(ui_BTN_Remove_Filament, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Remove_Filament, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Remove_Filament, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Remove_Filament, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Remove_Filament, 66);
    lv_obj_set_width(ui_BTN_Remove_Filament, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Remove_Filament, 360);
    lv_obj_set_y(ui_BTN_Remove_Filament, 40);
    lv_obj_set_align(ui_BTN_Remove_Filament, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Remove_Filament, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Remove_Filament, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Remove_Filament, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Remove_Filament, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Remove_Filament, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Remove_Filament, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Remove_Filament, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Remove_Filament = lv_label_create(ui_BTN_Remove_Filament);
    lv_obj_set_width(ui_Label_Remove_Filament, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Remove_Filament, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Remove_Filament, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Remove_Filament, _("Reset"));
    lv_label_set_recolor(ui_Label_Remove_Filament, "true");
    lv_obj_set_style_text_align(ui_Label_Remove_Filament, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Remove_Filament, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Slider = lv_obj_create(ui_S1_Content_Panel2);
    lv_obj_set_width(ui_Panel_Slider, 550);
    lv_obj_set_height(ui_Panel_Slider, 121);
    lv_obj_set_align(ui_Panel_Slider, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_bg_color(ui_Panel_Slider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider_Print_Speed = lv_slider_create(ui_Panel_Slider);
    lv_slider_set_range(ui_Slider_Print_Speed, -3, 3);
    lv_obj_set_width(ui_Slider_Print_Speed, 475);
    lv_obj_set_height(ui_Slider_Print_Speed, 35);
    lv_obj_set_align(ui_Slider_Print_Speed, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider_Print_Speed, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Print_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Slider_Print_Speed, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Slider_Print_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Slider_Print_Speed, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Slider_Print_Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider_Print_Speed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider_Print_Speed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider_Print_Speed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider_Print_Speed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Print_Speed, lv_color_hex(0x1DE8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Print_Speed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider_Print_Speed, lv_color_hex(0x0962B7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider_Print_Speed, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Print_Speed, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Print_Speed, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider_Print_Speed, lv_color_hex(0x556483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider_Print_Speed, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider_Print_Speed, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider_Print_Speed, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider_Print_Speed, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider_Print_Speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Slider_Print_Speed, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Slider_Print_Speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider_Print_Speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider_Print_Speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider_Print_Speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider_Print_Speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label_Print_Speed = lv_label_create(ui_Panel_Slider);
    lv_obj_set_width(ui_Label_Print_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Print_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Print_Speed, 25);
    lv_obj_set_y(ui_Label_Print_Speed, -10);
    lv_label_set_text(ui_Label_Print_Speed, _("Temperature Calibration"));
    lv_label_set_recolor(ui_Label_Print_Speed, "true");
    lv_obj_set_style_text_color(ui_Label_Print_Speed, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Print_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Print_Speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Print_Speed, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Print_Speed_Number = lv_label_create(ui_Panel_Slider);
    lv_obj_set_width(ui_Label_Print_Speed_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Print_Speed_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Print_Speed_Number, -30);
    lv_obj_set_y(ui_Label_Print_Speed_Number, -10);
    lv_obj_set_align(ui_Label_Print_Speed_Number, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label_Print_Speed_Number, "0 C°");
    lv_label_set_recolor(ui_Label_Print_Speed_Number, "true");
    lv_obj_set_style_text_color(ui_Label_Print_Speed_Number, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Print_Speed_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Print_Speed_Number, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Print_Speed_Number, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Swich_Group = lv_obj_create(ui_ScreenSetting);
    lv_obj_set_width(ui_Swich_Group, 160);
    lv_obj_set_height(ui_Swich_Group, 422);
    lv_obj_set_x(ui_Swich_Group, -20);
    lv_obj_set_y(ui_Swich_Group, 50);
    lv_obj_set_align(ui_Swich_Group, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Swich_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Swich_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Swich_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Swich_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Swich_Group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Swich_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Light = lv_label_create(ui_Swich_Group);
    lv_obj_set_width(ui_Label_Light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Light, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Light, _("Unit"));
    lv_label_set_recolor(ui_Label_Light, "true");
    lv_obj_set_style_text_color(ui_Label_Light, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Light, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Light, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Light = lv_switch_create(ui_Swich_Group);
    lv_obj_set_width(ui_Switch_Light, 90);
    lv_obj_set_height(ui_Switch_Light, 40);
    lv_obj_set_x(ui_Switch_Light, 0);
    lv_obj_set_y(ui_Switch_Light, 30);
    lv_obj_set_align(ui_Switch_Light, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_Switch_Light, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Switch_Light, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Light, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Light, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Light, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Light, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Light, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Light, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Light, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Light, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Light, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Light, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Light, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Light, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Light, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Light, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Light, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Light, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Light, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Light, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Light, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Light, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Light, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Light, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_Switch_Light, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_Switch_Light, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Light, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label_Celsius = lv_label_create(ui_Swich_Group);
    lv_obj_set_width(ui_Label_Celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Celsius, -10);
    lv_obj_set_y(ui_Label_Celsius, 40);
    lv_label_set_text(ui_Label_Celsius, "C°");
    lv_label_set_recolor(ui_Label_Celsius, "true");
    lv_obj_set_style_text_color(ui_Label_Celsius, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Celsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Celsius, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Celsius, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Farenheit = lv_label_create(ui_Swich_Group);
    lv_obj_set_width(ui_Label_Farenheit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Farenheit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Farenheit, 10);
    lv_obj_set_y(ui_Label_Farenheit, 40);
    lv_obj_set_align(ui_Label_Farenheit, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label_Farenheit, "F°");
    lv_label_set_recolor(ui_Label_Farenheit, "true");
    lv_obj_set_style_text_color(ui_Label_Farenheit, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Farenheit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Farenheit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Farenheit, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Demo_Mode = lv_label_create(ui_Swich_Group);
    lv_obj_set_width(ui_Label_Demo_Mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Demo_Mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Demo_Mode, 0);
    lv_obj_set_y(ui_Label_Demo_Mode, 100);
    lv_obj_set_align(ui_Label_Demo_Mode, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Demo_Mode, _("Demo Mode"));
    lv_label_set_recolor(ui_Label_Demo_Mode, "true");
    lv_obj_set_style_text_color(ui_Label_Demo_Mode, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Demo_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Demo_Mode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Demo_Mode, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Demo_Mode = lv_switch_create(ui_Swich_Group);
    lv_obj_set_width(ui_Switch_Demo_Mode, 90);
    lv_obj_set_height(ui_Switch_Demo_Mode, 40);
    lv_obj_set_x(ui_Switch_Demo_Mode, 0);
    lv_obj_set_y(ui_Switch_Demo_Mode, 130);
    lv_obj_set_align(ui_Switch_Demo_Mode, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Switch_Demo_Mode, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Demo_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Demo_Mode, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Demo_Mode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Demo_Mode, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Demo_Mode, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Demo_Mode, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Demo_Mode, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Demo_Mode, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Demo_Mode, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Demo_Mode, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Demo_Mode, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Demo_Mode, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Demo_Mode, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Demo_Mode, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Demo_Mode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Demo_Mode, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Demo_Mode, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Demo_Mode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Demo_Mode, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Demo_Mode, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Demo_Mode, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Demo_Mode, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Demo_Mode, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_Switch_Demo_Mode, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_Switch_Demo_Mode, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Demo_Mode, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label_Fan_2 = lv_label_create(ui_Swich_Group);
    lv_obj_set_width(ui_Label_Fan_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fan_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fan_2, 0);
    lv_obj_set_y(ui_Label_Fan_2, 200);
    lv_obj_set_align(ui_Label_Fan_2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Fan_2, _("Hi Limit Cut-OFF"));
    lv_label_set_recolor(ui_Label_Fan_2, "true");
    lv_obj_set_style_text_color(ui_Label_Fan_2, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fan_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Fan_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fan_2, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Fan_2 = lv_switch_create(ui_Swich_Group);
    lv_obj_set_width(ui_Switch_Fan_2, 90);
    lv_obj_set_height(ui_Switch_Fan_2, 40);
    lv_obj_set_x(ui_Switch_Fan_2, 0);
    lv_obj_set_y(ui_Switch_Fan_2, 230);
    lv_obj_set_align(ui_Switch_Fan_2, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_Switch_Fan_2, LV_STATE_CHECKED | LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_Switch_Fan_2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Fan_2, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Fan_2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Fan_2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Fan_2, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Fan_2, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_2, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Fan_2, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Fan_2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Fan_2, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Fan_2, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Fan_2, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_2, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Fan_2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Fan_2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_2, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Fan_2, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Fan_2, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Fan_2, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Fan_2, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_Switch_Fan_2, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_Switch_Fan_2, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_2, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label_Fan_3 = lv_label_create(ui_Swich_Group);
    lv_obj_set_width(ui_Label_Fan_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fan_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fan_3, 0);
    lv_obj_set_y(ui_Label_Fan_3, 300);
    lv_obj_set_align(ui_Label_Fan_3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Fan_3, _("Touch Screen"));
    lv_label_set_recolor(ui_Label_Fan_3, "true");
    lv_obj_set_style_text_color(ui_Label_Fan_3, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fan_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Fan_3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fan_3, &ui_font_Chinese_20_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Fan_3 = lv_switch_create(ui_Swich_Group);
    lv_obj_set_width(ui_Switch_Fan_3, 90);
    lv_obj_set_height(ui_Switch_Fan_3, 40);
    lv_obj_set_x(ui_Switch_Fan_3, 0);
    lv_obj_set_y(ui_Switch_Fan_3, 330);
    lv_obj_set_align(ui_Switch_Fan_3, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_Switch_Fan_3, LV_STATE_CHECKED | LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_Switch_Fan_3, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Fan_3, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Fan_3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Fan_3, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Fan_3, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Fan_3, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_3, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_3, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Fan_3, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Fan_3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Fan_3, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Fan_3, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Fan_3, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_3, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Fan_3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Fan_3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_3, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Fan_3, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Fan_3, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Fan_3, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Fan_3, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_Switch_Fan_3, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_Switch_Fan_3, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_3, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_BTNAutoMenuPrint2, ui_event_BTNAutoMenuPrint2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuMove2, ui_event_BTNAutoMenuMove2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller2, ui_event_Roller2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Heat_Head, ui_event_BTN_Heat_Head, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider_Print_Speed, ui_event_Slider_Print_Speed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Light, ui_event_Switch_Light, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_Demo_Mode, ui_event_Switch_Demo_Mode, LV_EVENT_ALL, NULL);

}
