// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenMenuConfigEditMenuSelect_screen_init(void)
{
    ui_ScreenMenuConfigEditMenuSelect = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenMenuConfigEditMenuSelect, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenuConfigEditMenuSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background6 = lv_img_create(ui_ScreenMenuConfigEditMenuSelect);
    lv_img_set_src(ui_Background6, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_Background6, 800);
    lv_obj_set_height(ui_Background6, 480);
    lv_obj_set_align(ui_Background6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNAutoMenuPrint7 = lv_img_create(ui_ScreenMenuConfigEditMenuSelect);
    lv_img_set_src(ui_BTNAutoMenuPrint7, &ui_img_photoshoped_assets_manual_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint7, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint7, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove7 = lv_img_create(ui_ScreenMenuConfigEditMenuSelect);
    lv_img_set_src(ui_BTNAutoMenuMove7, &ui_img_photoshoped_assets_timer_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuMove7, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove7, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove7, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuMove7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuSetting7 = lv_img_create(ui_ScreenMenuConfigEditMenuSelect);
    lv_img_set_src(ui_BTNAutoMenuSetting7, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting7, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting7, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting7, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header6 = lv_obj_create(ui_ScreenMenuConfigEditMenuSelect);
    lv_obj_set_width(ui_Panel_Header6, 665);
    lv_obj_set_height(ui_Panel_Header6, 39);
    lv_obj_set_x(ui_Panel_Header6, -30);
    lv_obj_set_y(ui_Panel_Header6, 0);
    lv_obj_set_align(ui_Panel_Header6, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header6 = lv_label_create(ui_Panel_Header6);
    lv_obj_set_width(ui_Label_Header6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header6, _("User Menu: Edit | Select menu"));
    lv_label_set_recolor(ui_Label_Header6, "true");
    lv_obj_set_style_text_color(ui_Label_Header6, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header6, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenMenuConfigDelMenu1 = lv_obj_create(ui_ScreenMenuConfigEditMenuSelect);
    lv_obj_set_width(ui_ScreenMenuConfigDelMenu1, 720);
    lv_obj_set_height(ui_ScreenMenuConfigDelMenu1, 430);
    lv_obj_set_align(ui_ScreenMenuConfigDelMenu1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ScreenMenuConfigDelMenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMenuConfigDelMenu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenMenuConfigDelMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenMenuConfigDelMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownEditMenuChoose = lv_dropdown_create(ui_ScreenMenuConfigDelMenu1);
    lv_dropdown_set_options(ui_DropdownEditMenuChoose,
                            "炸春捲\n炸雲吞\n炸餛飩\n炸魚\n炸蝦\n炸排骨\n炸花生\n炸蟹黃角\n炸豆腐\n炸雞翅中\n炸雞腿\n炸豆干\n炸薯條\n炸蘑菇\n炸茄盒\n炸豆皮卷\n炸脆皮腸\n炸海帶絲\n炸雞米花\n薯條\n洋蔥圈\n雞翅\n炸雞\n炸蝦\n芝士棒\n炸魚\n炸魷魚\n玉米狗\n土豆塊\n天婦羅\n雞條\n玉米球\n炸秋葵\n炸蘑菇\n炸蛤蜊\n炸牡蠣\n炸番茄\n炸春捲\n煎餃\n雞塊\n炸鯰魚\n炸魷魚\n油條");
    lv_obj_set_width(ui_DropdownEditMenuChoose, 190);
    lv_obj_set_height(ui_DropdownEditMenuChoose, 70);
    lv_obj_set_x(ui_DropdownEditMenuChoose, -150);
    lv_obj_set_y(ui_DropdownEditMenuChoose, -95);
    lv_obj_set_align(ui_DropdownEditMenuChoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownEditMenuChoose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownEditMenuChoose, lv_color_hex(0xDEE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownEditMenuChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownEditMenuChoose, &ui_font_Chinese_30_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownEditMenuChoose, lv_color_hex(0x181C20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownEditMenuChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DropdownEditMenuChoose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownEditMenuChoose, &lv_font_montserrat_30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownEditMenuChoose), &ui_font_Chinese_30_Bold,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRollerDeleteMenuChooseBTN1 = lv_obj_create(ui_ScreenMenuConfigDelMenu1);
    lv_obj_set_width(ui_PanelRollerDeleteMenuChooseBTN1, 180);
    lv_obj_set_height(ui_PanelRollerDeleteMenuChooseBTN1, 180);
    lv_obj_set_x(ui_PanelRollerDeleteMenuChooseBTN1, 150);
    lv_obj_set_y(ui_PanelRollerDeleteMenuChooseBTN1, 0);
    lv_obj_set_align(ui_PanelRollerDeleteMenuChooseBTN1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRollerDeleteMenuChooseBTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRollerDeleteMenuChooseBTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelRollerDeleteMenuChooseBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRollerDeleteMenuChooseBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNDeleteMenuChoose1 = lv_img_create(ui_PanelRollerDeleteMenuChooseBTN1);
    lv_img_set_src(ui_BTNDeleteMenuChoose1, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTNDeleteMenuChoose1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNDeleteMenuChoose1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNDeleteMenuChoose1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNDeleteMenuChoose1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNDeleteMenuChooseTop1 = lv_img_create(ui_BTNDeleteMenuChoose1);
    lv_img_set_src(ui_BTNDeleteMenuChooseTop1, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTNDeleteMenuChooseTop1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTNDeleteMenuChooseTop1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTNDeleteMenuChooseTop1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNDeleteMenuChooseTop1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTNDeleteMenuChooseTop1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTNDeleteMenuChooseTop1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTNDeleteMenuChooseTop1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNDeleteMenuChooseTop1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTNDeleteMenuChooseTop1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTNDeleteMenuChooseTop1, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTNDeleteMenuChooseTop1, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_BTNDeleteMenuChooseTop1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_BTNDeleteMenuChooseTop1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTNDeleteMenuChooseTop1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNDeleteMenuChooseTop1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNDeleteMenuChooseTop1, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNDeleteMenuChooseTop1, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_BTNDeleteMenuChooseTop1, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_BTNDeleteMenuChooseTop1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageBTNDeleteMenuChoose1 = lv_img_create(ui_BTNDeleteMenuChooseTop1);
    lv_img_set_src(ui_ImageBTNDeleteMenuChoose1, &ui_img_1158544786);
    lv_obj_set_width(ui_ImageBTNDeleteMenuChoose1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageBTNDeleteMenuChoose1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ImageBTNDeleteMenuChoose1, 0);
    lv_obj_set_y(ui_ImageBTNDeleteMenuChoose1, 1);
    lv_obj_set_align(ui_ImageBTNDeleteMenuChoose1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBTNDeleteMenuChoose1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_ImageBTNDeleteMenuChoose1, 200);
    lv_obj_set_style_img_recolor(ui_ImageBTNDeleteMenuChoose1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBTNDeleteMenuChoose1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTNAutoMenuPrint7, ui_event_BTNAutoMenuPrint7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuMove7, ui_event_BTNAutoMenuMove7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNDeleteMenuChooseTop1, ui_event_BTNDeleteMenuChooseTop1, LV_EVENT_ALL, NULL);

}
