// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "../ui.h"

void ui_ScreenMenuConfiguration_screen_init(void)
{
    ui_ScreenMenuConfiguration = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenMenuConfiguration, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenuConfiguration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background1 = lv_img_create(ui_ScreenMenuConfiguration);
    lv_img_set_src(ui_Background1, &ui_img_photoshoped_assets_chinese_backgorund_chinese_png);
    lv_obj_set_width(ui_Background1, 800);
    lv_obj_set_height(ui_Background1, 480);
    lv_obj_set_align(ui_Background1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTNAutoMenuPrint3 = lv_img_create(ui_ScreenMenuConfiguration);
    lv_img_set_src(ui_BTNAutoMenuPrint3, &ui_img_photoshoped_assets_manual_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuPrint3, 79);
    lv_obj_set_height(ui_BTNAutoMenuPrint3, 160);
    lv_obj_add_flag(ui_BTNAutoMenuPrint3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuPrint3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuPrint3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuMove3 = lv_img_create(ui_ScreenMenuConfiguration);
    lv_img_set_src(ui_BTNAutoMenuMove3, &ui_img_photoshoped_assets_timer_glow_png);
    lv_obj_set_width(ui_BTNAutoMenuMove3, 79);
    lv_obj_set_height(ui_BTNAutoMenuMove3, 162);
    lv_obj_set_align(ui_BTNAutoMenuMove3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNAutoMenuMove3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuMove3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuMove3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNAutoMenuSetting3 = lv_img_create(ui_ScreenMenuConfiguration);
    lv_img_set_src(ui_BTNAutoMenuSetting3, &ui_img_photoshoped_assets_traditional_chinese_settings_zh_chinese_png);
    lv_obj_set_width(ui_BTNAutoMenuSetting3, 79);
    lv_obj_set_height(ui_BTNAutoMenuSetting3, 160);
    lv_obj_set_align(ui_BTNAutoMenuSetting3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNAutoMenuSetting3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTNAutoMenuSetting3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTNAutoMenuSetting3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header1 = lv_obj_create(ui_ScreenMenuConfiguration);
    lv_obj_set_width(ui_Panel_Header1, 665);
    lv_obj_set_height(ui_Panel_Header1, 39);
    lv_obj_set_x(ui_Panel_Header1, -30);
    lv_obj_set_y(ui_Panel_Header1, 0);
    lv_obj_set_align(ui_Panel_Header1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header1 = lv_label_create(ui_Panel_Header1);
    lv_obj_set_width(ui_Label_Header1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header1, _("User Menu: Create | Edit | Delete"));
    lv_label_set_recolor(ui_Label_Header1, "true");
    lv_obj_set_style_text_color(ui_Label_Header1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header1, &ui_font_Chinese_25_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1_Content_Panel1 = lv_obj_create(ui_ScreenMenuConfiguration);
    lv_obj_set_width(ui_S1_Content_Panel1, 720);
    lv_obj_set_height(ui_S1_Content_Panel1, 430);
    lv_obj_set_align(ui_S1_Content_Panel1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_S1_Content_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddMenuToJSON = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_AddMenuToJSON, lv_pct(31));
    lv_obj_set_height(ui_AddMenuToJSON, lv_pct(92));
    lv_obj_set_x(ui_AddMenuToJSON, 7);
    lv_obj_set_y(ui_AddMenuToJSON, 0);
    lv_obj_set_align(ui_AddMenuToJSON, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_AddMenuToJSON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddMenuToJSON, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddMenuToJSON, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AddMenuToJSON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AddMenuToJSON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AddMenuToJSON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AddMenuToJSON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AddMenuToJSON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AddMenuToJSON, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AddMenuToJSON, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNewMenu = lv_label_create(ui_AddMenuToJSON);
    lv_obj_set_width(ui_LabelNewMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNewMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNewMenu, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNewMenu, _("Create\nMenu"));
    lv_label_set_recolor(ui_LabelNewMenu, "true");
    lv_obj_set_style_text_color(ui_LabelNewMenu, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNewMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNewMenu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNewMenu, &ui_font_Chinese_30_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_AddMenuToJSON);
    lv_img_set_src(ui_Image5, &ui_img_1627854363);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EditMenuToJSON = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_EditMenuToJSON, lv_pct(31));
    lv_obj_set_height(ui_EditMenuToJSON, lv_pct(92));
    lv_obj_set_x(ui_EditMenuToJSON, -3);
    lv_obj_set_y(ui_EditMenuToJSON, 0);
    lv_obj_set_align(ui_EditMenuToJSON, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EditMenuToJSON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EditMenuToJSON, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EditMenuToJSON, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_EditMenuToJSON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_EditMenuToJSON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EditMenuToJSON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_EditMenuToJSON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_EditMenuToJSON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_EditMenuToJSON, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_EditMenuToJSON, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEditMenu = lv_label_create(ui_EditMenuToJSON);
    lv_obj_set_width(ui_LabelEditMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEditMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEditMenu, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelEditMenu, _("Edit\nMenu"));
    lv_label_set_recolor(ui_LabelEditMenu, "true");
    lv_obj_set_style_text_color(ui_LabelEditMenu, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEditMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEditMenu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEditMenu, &ui_font_Chinese_30_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_EditMenuToJSON);
    lv_img_set_src(ui_Image4, &ui_img_1688661777);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DeleteMenuToJSON = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_DeleteMenuToJSON, lv_pct(31));
    lv_obj_set_height(ui_DeleteMenuToJSON, lv_pct(92));
    lv_obj_set_x(ui_DeleteMenuToJSON, -10);
    lv_obj_set_y(ui_DeleteMenuToJSON, 0);
    lv_obj_set_align(ui_DeleteMenuToJSON, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_DeleteMenuToJSON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeleteMenuToJSON, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteMenuToJSON, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DeleteMenuToJSON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DeleteMenuToJSON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DeleteMenuToJSON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DeleteMenuToJSON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DeleteMenuToJSON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DeleteMenuToJSON, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DeleteMenuToJSON, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDeleteMenu = lv_label_create(ui_DeleteMenuToJSON);
    lv_obj_set_width(ui_LabelDeleteMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDeleteMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDeleteMenu, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDeleteMenu, _("Delete\nMenu"));
    lv_label_set_recolor(ui_LabelDeleteMenu, "true");
    lv_obj_set_style_text_color(ui_LabelDeleteMenu, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDeleteMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDeleteMenu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDeleteMenu, &ui_font_Chinese_30_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_DeleteMenuToJSON);
    lv_img_set_src(ui_Image6, &ui_img_1244952608);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTNAutoMenuPrint3, ui_event_BTNAutoMenuPrint3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNAutoMenuMove3, ui_event_BTNAutoMenuMove3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AddMenuToJSON, ui_event_AddMenuToJSON, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EditMenuToJSON, ui_event_EditMenuToJSON, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeleteMenuToJSON, ui_event_DeleteMenuToJSON, LV_EVENT_ALL, NULL);

}
