// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: 3d_printer

#include "ui.h"

void MenuStartCookingButtonManual(lv_event_t * e)
{
	// Your code here
}

void ManualSetTargetTemperature(lv_event_t * e)
{
	// Your code here
}

void ManualSetCountdownTime(lv_event_t * e)
{
	// Your code here
}

void MenuStartCookingButtonAuto(lv_event_t * e)
{
	// Your code here
}

void Roller_Option_Menu_Change(lv_event_t * e)
{
	// Your code here
}

void Change_Language_From_Settings(lv_event_t * e)
{
	// Your code here
}

void Temperature_Unit_Change(lv_event_t * e)
{
	// Your code here
}

void DemoModeOnOFF(lv_event_t * e)
{
	// Your code here
}

void CreateNewMenu(lv_event_t * e)
{
	// Your code here
}

void CreateMenuChangeTemperature(lv_event_t * e)
{
	// Your code here
}

void CreateMenuSetCountdownTime(lv_event_t * e)
{
	// Your code here
}

void DeleteCurrentMenu(lv_event_t * e)
{
	// Your code here
}

void EditCurrentMenuSelect(lv_event_t * e)
{
	// Your code here
}

void EditCurrentMenu(lv_event_t * e)
{
	// Your code here
}

void EditMenuTargetTemperatureSlider(lv_event_t * e)
{
	// Your code here
}

void EditSetCountdownTime(lv_event_t * e)
{
	// Your code here
}

void Screensaver_Menu_Event(lv_event_t * e)
{
	// Your code here
}

void DropFoodReminderDone(lv_event_t * e)
{
	// Your code here
}
